### ISSUE TITLE
Streaming in browser

### ISSUE THREAD

**Issue by matrixik** [HichuYamichu/radio-app#1]
Hi,
Thank you for creating this small app.

Would it be possible to allow streaming in browser?
Now whenever I'm trying to use e.g. `<audio>` tag or something like https://www.muses.org/ , app is starting to use entire core and nothing is played. But I can play it in `cvcl` command line player without much problems.

**Comment by HichuYamichu** [comment]
Try:
```html
<audio autoplay src="http://localhost:3000" type="audio/wav" ></audio>
```
It takes a short while for the browser to figure out live audio stream, so playback is delayed. Give it like 1-2 seconds and it should start playing normally.

**Comment by matrixik** [comment]
Thank you for reply.

I changed `server.go` file to using 
```
    <audio controls>
        <source src="/audio" type="audio/wav">
        Your browser does not support the audio element.
    </audio>
```
[server.go.txt](https://github.com/HichuYamichu/radio-app/files/3829122/server.go.txt)

It still did not worked in Firefox so checked in Chrome and there it's working. Strange.

**Comment by matrixik** [comment]
Oh, when I close page in Chrome then it starting to use entire CPU core, probably some problem with killing connection.

Probably need something like in https://github.com/VivaLaPanda/uta-stream/blob/master/stream/serve.go

No time today for looking into it anymore. Thank you for your help.
